apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: cortex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cortex
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: v1.21.0
    helm.sh/chart: cortex-3.3.0
  name: alertmanager-nodeport
  namespace: cortex
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30006
  selector:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: cortex
    app.kubernetes.io/name: cortex
  type: NodePort
status:
  loadBalancer: {}
