apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: storage

spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /data/minio

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: storage

spec:
  capacity:
    storage: 2Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /data/grafana

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: storage

spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /data/prometheus
