apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring

data:
  prometheus.yml: |
    global:
      scrape_interval: 30s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

      - job_name: 'node-exporter'
        static_configs:
          - targets:
              - 192.168.100.10:9100
              - 192.168.100.11:9100
              - 192.168.100.12:9100

    remote_write:
      - url: http://cortex-nginx.cortex.svc.cluster.local/api/prom/push
