apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring

data:
  prometheus.yml: |
    global:
      scrape_interval: 30s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

    remote_write:
      - url: http://cortex-nginx.cortex.svc.cluster.local/api/prom/push
