apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  volumeName: prometheus-pv

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring

spec:
  replicas: 1

  selector:
    matchLabels:
      app: prometheus

  template:
    metadata:
      labels:
        app: prometheus

    spec:
      serviceAccountName: prometheus

      containers:
      - name: prometheus

        image: prom/prometheus:latest

        args:
          - --config.file=/etc/prometheus/prometheus.yml
          - --storage.tsdb.path=/prometheus

        ports:
          - containerPort: 9090

        volumeMounts:
          - name: config
            mountPath: /etc/prometheus

          - name: alerts
            mountPath: /etc/prometheus/rules

          - name: prometheus-storage
            mountPath: /prometheus

      volumes:
        - name: config

          configMap:
            name: prometheus-config

        - name: alerts

          configMap:
            name: prometheus-alerts

        - name: prometheus-storage

          persistentVolumeClaim:
            claimName: prometheus-pvc
